In [358]:
from pathlib import Path
import pandas as pd

In [359]:
def ler_arquivo_csv(nome_arquivo, sep=',', encoding='latin-1'):

    caminho_notebook = Path.cwd()
    caminho_relativo_csv = f'./data/{nome_arquivo}.csv'
    caminho_raiz = caminho_notebook.parent
    caminho_abs_csv = caminho_raiz / caminho_relativo_csv

    try:
        df = pd.read_csv(caminho_abs_csv, sep=sep, encoding=encoding, low_memory=False)
        return df
    except FileNotFoundError:
        print(f"O arquivo CSV não foi encontrado em {caminho_abs_csv}")

In [361]:
df = ler_arquivo_csv('INFLUD19', sep=';')
df

DT_NOTIFIC  SEM_NOT  DT_SIN_PRI  SEM_PRI SG_UF_NOT  \
0      10/01/2019        2  06/01/2019        2        MG   
1      03/01/2019        1  01/01/2019        1        SP   
2      02/01/2019        1  31/12/2018        1        PE   
3      10/01/2019        2  07/01/2019        2        SP   
4      11/01/2019        2  06/01/2019        2        PE   
...           ...      ...         ...      ...       ...   
48523  12/12/2019       50  09/12/2019       50        BA   
48524  05/11/2019       45  23/10/2019       43        PA   
48525  11/04/2020       15  26/12/2019       52        SP   
48526  31/10/2019       44  29/10/2019       44        BA   
48527  08/04/2020       15  01/12/2019       49        ES   

                              ID_REGIONA  CO_REGIONA      ID_MUNICIP  \
0                         BELO HORIZONTE      1449.0  BELO HORIZONTE   
1                          GVE I CAPITAL      1331.0       SAO PAULO   
2                                      1      1497.0          RECIFE   
3                      GVE XVII CAMPINAS      1342.0        CAMPINAS   
4                                      4      1499.0         CARUARU   
...                                  ...         ...             ...   
48523     NUCLEO REGIONAL DE SAUDE LESTE      1380.0        SALVADOR   
48524     04 REGIONAL DE PROTECAO SOCIAL      1487.0        CAPANEMA   
48525                     GVE XXV SANTOS      1349.0         GUARUJA   
48526  NUCLEO REGIONAL DE SAUDE SUDOESTE      1398.0         BRUMADO   
48527                      METROPOLITANA      1510.0           SERRA   

       CO_MUN_NOT                                         ID_UNIDADE  ...  \
0          310620                UNIDADE DE PRONTO ATENDIMENTO LESTE  ...   
1          355030                               HOSP MUN M BOI MIRIM  ...   
2          261160                                               IMIP  ...   
3          350950         HOSPITAL MUNICIPAL DR MARIO GATTI CAMPINAS  ...   
4          260410           SECRETARIA MUNICIPAL DE SAUDE DE CARUARU  ...   
...           ...                                                ...  ...   
48523      292740                 HOSPITAL MUNICIPAL DE SALVADOR HMS  ...   
48524      150220                           ASSOCIACAO GUIOMAR JESUS  ...   
48525      351870  PRONTO SOCORRO PROF DR MATHEUS SANTAMARIA GUARUJA  ...   
48526      290460             HOSPITAL MUNICIPAL PROF MAGALHAES NETO  ...   
48527      320500                         VITORIA APART HOSPITAL S A  ...   

        DT_DIGITA HISTO_VGM PAIS_VGM  CO_PS_VGM  LO_PS_VGM  DT_VGM  DT_RT_VGM  \
0      14/03/2019         0      NaN        NaN        NaN     NaN        NaN   
1             NaN         0      NaN        NaN        NaN     NaN        NaN   
2             NaN         0      NaN        NaN        NaN     NaN        NaN   
3             NaN         0      NaN        NaN        NaN     NaN        NaN   
4             NaN         0      NaN        NaN        NaN     NaN        NaN   
...           ...       ...      ...        ...        ...     ...        ...   
48523  09/04/2020         2      NaN        NaN        NaN     NaN        NaN   
48524  11/04/2020         2      NaN        NaN        NaN     NaN        NaN   
48525  13/04/2020         2      NaN        NaN        NaN     NaN        NaN   
48526  13/04/2020         9      NaN        NaN        NaN     NaN        NaN   
48527  15/04/2020         2      NaN        NaN        NaN     NaN        NaN   

       PCR_SARS2  PAC_COCBO PAC_DSCBO  
0            NaN        NaN       NaN  
1            NaN        NaN       NaN  
2            NaN        NaN       NaN  
3            NaN        NaN       NaN  
4            NaN        NaN       NaN  
...          ...        ...       ...  
48523        NaN        NaN       NaN  
48524        NaN        NaN       NaN  
48525        NaN        NaN       NaN  
48526        NaN        NaN       NaN  
48527        NaN        NaN       NaN  

[48528 rows x 137 columns]

In [362]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48528 entries, 0 to 48527
Columns: 137 entries, DT_NOTIFIC to PAC_DSCBO
dtypes: float64(84), int64(9), object(44)
memory usage: 50.7+ MB


In [151]:
# escolhi trabalhar com as seguintes colunas.

lista_colunas = [
    'DT_NOTIFIC',
    'SG_UF_NOT',
    'ID_MUNICIP',
    'CS_SEXO',
    'DT_NASC',
    'NU_IDADE_N',
    'CS_RACA',
    'CS_ESCOL_N',
    'CS_ZONA',
    'FEBRE',
    'TOSSE',
    'GARGANTA',
    'DISPNEIA',
    'OBESIDADE',
    'DIABETES',
    'PNEUMOPATI',
    'IMUNODEPRE'
]


In [152]:
df_versao1 = df[lista_colunas]
df_versao1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48528 entries, 0 to 48527
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   DT_NOTIFIC  48528 non-null  object 
 1   SG_UF_NOT   48528 non-null  object 
 2   ID_MUNICIP  48528 non-null  object 
 3   CS_SEXO     48528 non-null  object 
 4   DT_NASC     48361 non-null  object 
 5   NU_IDADE_N  48528 non-null  int64  
 6   CS_RACA     46626 non-null  float64
 7   CS_ESCOL_N  44856 non-null  float64
 8   CS_ZONA     47304 non-null  float64
 9   FEBRE       48341 non-null  float64
 10  TOSSE       48317 non-null  float64
 11  GARGANTA    47360 non-null  float64
 12  DISPNEIA    48120 non-null  float64
 13  OBESIDADE   18223 non-null  float64
 14  DIABETES    18526 non-null  float64
 15  PNEUMOPATI  18533 non-null  float64
 16  IMUNODEPRE  18410 non-null  float64
dtypes: float64(11), int64(1), object(5)
memory usage: 6.3+ MB


# Verificação e tratamento de valores Nan

In [153]:
df_versao1.isna().sum()

DT_NOTIFIC        0
SG_UF_NOT         0
ID_MUNICIP        0
CS_SEXO           0
DT_NASC         167
NU_IDADE_N        0
CS_RACA        1902
CS_ESCOL_N     3672
CS_ZONA        1224
FEBRE           187
TOSSE           211
GARGANTA       1168
DISPNEIA        408
OBESIDADE     30305
DIABETES      30002
PNEUMOPATI    29995
IMUNODEPRE    30118
dtype: int64

### Tratar os valores Nan no dataframe reduzido

Tratar os valores NaN da coluna CS_RACA (Campo Essencial) para  o valor padrão (ignorado)

**lista de tipos de raça:**

1. Branca
2. Preta
3. Amarela
4. Parda
5. Indígena
9. Ignorado

In [154]:
df_versao1['CS_RACA'].unique()

array([ 1.,  4., nan,  2.,  9.,  3.,  5.])

In [155]:
# campos Nan receberam o valor (9-Ignorado) segundo documento.

filter_raca_na = df_versao1['CS_RACA'].isna()
df_versao1.loc[filter_raca_na, 'CS_RACA'] = 9.0


In [156]:
df_versao1.loc[filter, 'CS_RACA'].isna().sum()

df_versao1.isna().sum()

DT_NOTIFIC        0
SG_UF_NOT         0
ID_MUNICIP        0
CS_SEXO           0
DT_NASC         167
NU_IDADE_N        0
CS_RACA           0
CS_ESCOL_N     3672
CS_ZONA        1224
FEBRE           187
TOSSE           211
GARGANTA       1168
DISPNEIA        408
OBESIDADE     30305
DIABETES      30002
PNEUMOPATI    29995
IMUNODEPRE    30118
dtype: int64

Documentação: Preenchido automaticamente com a categoria “não se aplica” quando idade
**for menor que 7 anos**
**Quando idade for maior**
que 7 anos, o campo não pode ser preenchido com “não se aplica”

0. Sem escolaridade/Analfabeto
1. Fundamental 1º ciclo (1ª a 5ª série)
2. Fundamental 2º ciclo (6ª a 9ª série)
3. Médio (1º ao 3º ano)
4. Superior
5. Não se aplica
9. Ignorado


In [157]:
df_versao1['CS_ESCOL_N'].isna()

filter_escolaridade_na = df_versao1['CS_ESCOL_N'].isna()

In [186]:
# filtro de paciente maiores que 7 anos
filter_idade_maior_sete = (df_versao1['NU_IDADE_N'] > 7)

In [187]:
# Substitui os valores Nan da coluna 'CS_ESCOL_N' baseado na docmentação.
df_versao1.loc[filter_idade_maior_sete, 'CS_ESCOL_N'] = df_versao1.loc[filter_idade_maior_sete, 'CS_ESCOL_N'].fillna(9.0)

In [188]:
df_versao1.isna().sum()

DT_NOTIFIC        0
SG_UF_NOT         0
ID_MUNICIP        0
CS_SEXO           0
DT_NASC         167
NU_IDADE_N        0
CS_RACA           0
CS_ESCOL_N     1166
CS_ZONA        1224
FEBRE           187
TOSSE           211
GARGANTA       1168
DISPNEIA        408
OBESIDADE     30305
DIABETES      30002
PNEUMOPATI    29995
IMUNODEPRE    30118
dtype: int64

In [191]:
df_versao1['CS_ESCOL_N'].unique()

array([ 2.,  5., nan,  3.,  1.,  9.,  0.,  4.])

In [197]:
filter_idade_menor_sete = (df_versao1['NU_IDADE_N'] <= 7)
df_versao1[filter_idade_menor_sete]['CS_ESCOL_N'].isna().sum()

np.int64(1166)

In [206]:
df_versao1.loc[filter_idade_menor_sete, 'CS_ESCOL_N'] = df_versao1.loc[filter_idade_menor_sete, 'CS_ESCOL_N'].fillna(5.0)

In [208]:
df_versao1.isna().sum()

DT_NOTIFIC        0
SG_UF_NOT         0
ID_MUNICIP        0
CS_SEXO           0
DT_NASC         167
NU_IDADE_N        0
CS_RACA           0
CS_ESCOL_N        0
CS_ZONA        1224
FEBRE           187
TOSSE           211
GARGANTA       1168
DISPNEIA        408
OBESIDADE     30305
DIABETES      30002
PNEUMOPATI    29995
IMUNODEPRE    30118
dtype: int64

Zona geográfica do endereço de residência do paciente

1. Urbana
2. Rural
3. Periurbana
9. Ignorado

In [211]:
df_versao1['CS_ZONA'].unique()

array([ 1.,  2., nan,  3.])

In [220]:
filter_zona = df_versao1['CS_ZONA'].isna()

df_versao1.loc[filter_zona, 'CS_ZONA'] = df_versao1.loc[filter_zona, 'CS_ZONA'].fillna(9.0)


In [221]:
df_versao1.isna().sum()

DT_NOTIFIC        0
SG_UF_NOT         0
ID_MUNICIP        0
CS_SEXO           0
DT_NASC         167
NU_IDADE_N        0
CS_RACA           0
CS_ESCOL_N        0
CS_ZONA           0
FEBRE           187
TOSSE           211
GARGANTA       1168
DISPNEIA        408
OBESIDADE     30305
DIABETES      30002
PNEUMOPATI    29995
IMUNODEPRE    30118
dtype: int64

Paciente apresentou febre?

1. Sim
2. Não
9. Ignorado

In [223]:
df_versao1['FEBRE'].unique()

array([ 1.,  2.,  9., nan])

In [225]:
filter_febre = df_versao1['FEBRE'].isna()

df_versao1.loc[filter_febre, 'FEBRE'] = df_versao1.loc[filter_febre, 'FEBRE'].fillna(9.0)


In [226]:
df_versao1.isna().sum()

DT_NOTIFIC        0
SG_UF_NOT         0
ID_MUNICIP        0
CS_SEXO           0
DT_NASC         167
NU_IDADE_N        0
CS_RACA           0
CS_ESCOL_N        0
CS_ZONA           0
FEBRE             0
TOSSE           211
GARGANTA       1168
DISPNEIA        408
OBESIDADE     30305
DIABETES      30002
PNEUMOPATI    29995
IMUNODEPRE    30118
dtype: int64

#### Criei uma função **substituindo_valores_nan()** para substituir os valores Nan das colunas float e que tem 3 tipos de valores (1,2,9)

1-Sim
2-Não
9-Ignorado

Aqueles valores 'Nan' substitui pelo valor 9.0 (ignorado)

In [227]:
lista_colunas_com_nan = [
    'TOSSE',
    'GARGANTA',
    'DISPNEIA',
    'OBESIDADE',
    'DIABETES',
    'PNEUMOPATI',
    'IMUNODEPRE'
]

def substituindo_valores_nan(dataframe, lista_colunas):

    for coluna in dataframe[lista_colunas]:

        valores = len(list(dataframe[coluna].unique()))

        if (dataframe[coluna].dtypes == 'float64') & (valores == 4):

            filter = dataframe[coluna].isna()
            dataframe.loc[filter, coluna] = dataframe.loc[filter, coluna].fillna(9.0)

    return dataframe

df_versao2 = substituindo_valores_nan(df_versao1, lista_colunas_com_nan)

df_versao2.isna().sum()

DT_NOTIFIC      0
SG_UF_NOT       0
ID_MUNICIP      0
CS_SEXO         0
DT_NASC       167
NU_IDADE_N      0
CS_RACA         0
CS_ESCOL_N      0
CS_ZONA         0
FEBRE           0
TOSSE           0
GARGANTA        0
DISPNEIA        0
OBESIDADE       0
DIABETES        0
PNEUMOPATI      0
IMUNODEPRE      0
dtype: int64

In [230]:
df_versao2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48528 entries, 0 to 48527
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   DT_NOTIFIC  48528 non-null  object 
 1   SG_UF_NOT   48528 non-null  object 
 2   ID_MUNICIP  48528 non-null  object 
 3   CS_SEXO     48528 non-null  object 
 4   DT_NASC     48361 non-null  object 
 5   NU_IDADE_N  48528 non-null  int64  
 6   CS_RACA     48528 non-null  float64
 7   CS_ESCOL_N  48528 non-null  float64
 8   CS_ZONA     48528 non-null  float64
 9   FEBRE       48528 non-null  float64
 10  TOSSE       48528 non-null  float64
 11  GARGANTA    48528 non-null  float64
 12  DISPNEIA    48528 non-null  float64
 13  OBESIDADE   48528 non-null  float64
 14  DIABETES    48528 non-null  float64
 15  PNEUMOPATI  48528 non-null  float64
 16  IMUNODEPRE  48528 non-null  float64
dtypes: float64(11), int64(1), object(5)
memory usage: 6.3+ MB


NoneType

In [282]:
df_versao2['DT_NASC']

0        17/03/1988
1        30/05/2018
2        07/05/2017
3        15/07/2018
4        15/09/2018
            ...    
48523    29/11/2010
48524    07/07/1947
48525    13/12/1947
48526    07/05/1966
48527    16/07/1933
Name: DT_NASC, Length: 48528, dtype: object

In [289]:
filter_dt_nascimento_na = df_versao2['DT_NASC'].isna()

# salvar dados atualizadosem arquivo csv

In [363]:
caminho_raiz = Path.cwd().parent
caminho_data = caminho_raiz / 'data'

df_versao2.to_csv(f'{caminho_data}/srag_2019.csv', sep=',', encoding='latin-1', index=False)

df_srag_2019 = ler_arquivo_csv('srag_2019', sep=',')
df_srag_2019

DT_NOTIFIC SG_UF_NOT      ID_MUNICIP CS_SEXO     DT_NASC  NU_IDADE_N  \
0      10/01/2019        MG  BELO HORIZONTE       M  17/03/1988          30   
1      03/01/2019        SP       SAO PAULO       F  30/05/2018           7   
2      02/01/2019        PE          RECIFE       M  07/05/2017           1   
3      10/01/2019        SP        CAMPINAS       F  15/07/2018           5   
4      11/01/2019        PE         CARUARU       F  15/09/2018           3   
...           ...       ...             ...     ...         ...         ...   
48523  12/12/2019        BA        SALVADOR       M  29/11/2010           9   
48524  05/11/2019        PA        CAPANEMA       F  07/07/1947          72   
48525  11/04/2020        SP         GUARUJA       M  13/12/1947          72   
48526  31/10/2019        BA         BRUMADO       F  07/05/1966          53   
48527  08/04/2020        ES           SERRA       M  16/07/1933          86   

       CS_RACA  CS_ESCOL_N  CS_ZONA  FEBRE  TOSSE  GARGANTA  DISPNEIA  \
0          1.0         2.0      1.0    1.0    1.0       2.0       1.0   
1          1.0         5.0      1.0    1.0    1.0       2.0       1.0   
2          4.0         5.0      1.0    1.0    1.0       2.0       1.0   
3          1.0         5.0      1.0    1.0    1.0       9.0       1.0   
4          4.0         5.0      1.0    1.0    2.0       2.0       1.0   
...        ...         ...      ...    ...    ...       ...       ...   
48523      4.0         0.0      1.0    1.0    1.0       9.0       1.0   
48524      4.0         1.0      2.0    1.0    1.0       2.0       1.0   
48525      4.0         9.0      1.0    2.0    1.0       1.0       1.0   
48526      4.0         1.0      2.0    1.0    1.0       9.0       1.0   
48527      4.0         9.0      2.0    1.0    1.0       2.0       1.0   

       OBESIDADE  DIABETES  PNEUMOPATI  IMUNODEPRE  
0            9.0       9.0         9.0         9.0  
1            9.0       9.0         9.0         9.0  
2            9.0       9.0         9.0         9.0  
3            9.0       9.0         9.0         9.0  
4            9.0       9.0         9.0         9.0  
...          ...       ...         ...         ...  
48523        9.0       9.0         9.0         9.0  
48524        2.0       1.0         2.0         2.0  
48525        9.0       9.0         9.0         9.0  
48526        9.0       9.0         9.0         9.0  
48527        2.0       2.0         2.0         2.0  

[48528 rows x 17 columns]

In [356]:
df_srag_2019.describe()

NU_IDADE_N       CS_RACA    CS_ESCOL_N       CS_ZONA         FEBRE  \
count  48528.000000  48528.000000  48528.000000  48528.000000  48528.000000   
mean      26.373228      3.320207      5.076719      1.265414      1.178103   
std       28.118350      2.788900      2.668662      1.272288      0.787099   
min        0.000000      1.000000      0.000000      1.000000      1.000000   
25%        3.000000      1.000000      3.000000      1.000000      1.000000   
50%       10.000000      2.000000      5.000000      1.000000      1.000000   
75%       50.000000      4.000000      5.000000      1.000000      1.000000   
max      108.000000      9.000000      9.000000      9.000000      9.000000   

              TOSSE      GARGANTA      DISPNEIA     OBESIDADE      DIABETES  \
count  48528.000000  48528.000000  48528.000000  48528.000000  48528.000000   
mean       1.132336      2.482443      1.273450      6.420211      6.287339   
std        0.759986      2.125598      0.992827      3.394720      3.496659   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%        1.000000      2.000000      1.000000      2.000000      2.000000   
50%        1.000000      2.000000      1.000000      9.000000      9.000000   
75%        1.000000      2.000000      1.000000      9.000000      9.000000   
max        9.000000      9.000000      9.000000      9.000000      9.000000   

         PNEUMOPATI    IMUNODEPRE  
count  48528.000000  48528.000000  
mean       6.299044      6.351364  
std        3.485547      3.439295  
min        1.000000      1.000000  
25%        2.000000      2.000000  
50%        9.000000      9.000000  
75%        9.000000      9.000000  
max        9.000000      9.000000